# -*- coding: utf-8 -*-
"""Advanced GenAI internship Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ClUPFSLMJLXd26elpjWh2EO0Zk4z5-sl

**Logic Building Task – 1**

**1. User Login Check**

**Problem Statement** : Given a username and password, check whether login is successful. username = "admin" password = "1234"

**Requirements:** Print "Login Successful" if both username and password match Otherwise print "Invalid Credentials" Real-World Application: Authentication systems
"""

# stored credentials
username = "admin"
password = "1234"

# taking user input
entered_username = input("Enter username: ")
entered_password = input("Enter password: ")

# checking login
if entered_username == username and entered_password == password:
    print("Login Successful")
else:
    print("Invalid Credentials")

"""**2. Pass / Fail Analyzer**

**Problem Statement:** Analyze student results. marks = [45, 78, 90, 33, 60]

**Requirements:** A student passes if marks ≥ 50 Count the total number of pass students Count the total number of fail students Print the final result clearly Real-World Application: Academic evaluation systems
"""

#input a list of marks
marks = [45, 78, 90, 33, 60]

#count the total number of pass and fail students
total_pass = sum(1 for mark in marks if mark >= 50)
total_fail = sum(1 for mark in marks if mark < 50)

#Printing the final result
print(f"Count the total number of pass students : {total_pass}")
print(f"Count the total number of fail students : {total_fail}")

"""**3. Simple Data Cleaner**

**Problem Statement:**  Clean and standardize user names. names = [" Alice ", "bob", " CHARLIE "]

**Requirements:** Remove extra spaces Convert all names to lowercase Print the cleaned list Real-World Application: Data preprocessing before analysis
"""

#input a list of names
names = [" Alice ", "bob", " CHARLIE "]

## Create an empty list to store cleaned names
cleaned_list=[]

# Loop through each name in the original list
for name in names:

    # Remove leading and trailing spaces using strip()
    # Convert the name to lowercase using lower()
    cleaned_usernames =name.strip().lower()

    # Add the cleaned name to the new list
    cleaned_list.append(cleaned_usernames)

# Print the final cleaned list
print(cleaned_list)

"""**4. Message Length Analyzer**

**Problem Statement:** Analyze message sizes. messages = ["Hi", "Welcome to the platform", "OK"]

**Requirements:** Print messages = ["Hi", "Welcome to the platform", "OK"] Flag messages longer than 10 characters Real-World Application: Text filtering and validation systems
"""

# Given messages
messages = ["Hi", "Welcome to the platform", "OK"]

# Print the messages
print(f"messages: {messages}")

# Check each message length and print those that are longer than 10 characters
Flag = [msge for msge in messages if len(msge)>10]
print("Messages longer than 10 characters:" ,Flag)

"""**5. Error Message Detector**

**Problem Statement:** Detect error messages from system logs. logs = ["INFO", "ERROR", "WARNING", "ERROR"]

**Requirements:** Count the number of "ERROR" entries Print the total error count Real-World Application: Monitoring and log analysis systems
"""

## System logs
logs = ["INFO", "ERROR", "WARNING", "error"]

#Count the number of "ERROR" entries in the logs list, ignoring case sensitivity
error_count = sum(1 for log in logs if log.upper() == "ERROR")

#Printing the total error count
print("The total ERROR count:", error_count)