# -*- coding: utf-8 -*-
"""Task 2: Feb Internship Logic Building Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pV13WV_jwZ24_uOURXEWkqS1lGeAD9bF

**Task 2: Feb Internship Logic Building Task**

**Problem 1: Unique Words in a Sentence**

**Requirements** :
Given a sentence, identify all unique words and display:
1.The count of unique words
2.The unique words themselves
"""

# Take given input
sentence = input("Enter sentence: ")
# Convert sentence to list of words by splitting into individual words using split method
words = sentence.split()
# Convert list to set to remove duplicates and place only unique words
unique_words = set(words)
# Count unique words present in the set using length mentod of a set
count = len(unique_words)
# Display result of count and unique-words in set:
print("Unique Words count:", count)
print("Unique Words:", unique_words)

"""**Problem 2: Highest Salary from Employee Data**

**Problem Statement** :Store employee names and their salaries, and determine which employee has the highest salary.

**Requirements :**
A dictionary where:
Keys represent employee names
Values represent employee salaries
"""

# Dictionary storing employee name and salary from a given data
employees = {
    "Ravi": 75000,
    "Anita": 68000,
    "Kiran": 72000 }
# Assume 1st employee has highest salary and the name is an empty string
highest_name = ""
highest_salary = 0
# Loop through dictionary to check the maximum salary
for name in employees:
  salary=employees[name]
# Check if salary is greater than highest salary
  if salary > highest_salary:
        highest_salary = employees[name]
        highest_name = name
# Display result of highest salary with their name :
print("Highest Salary:", highest_name, "-", highest_salary)

"""**Problem 3: Find Maximum and Minimum Values**

**Problem Statement** : Find the maximum and minimum values from a list of numbers.

**requirements** : A list of integers where each element represents a numeric value.
"""

# List of numbers given
numbers = [45, 22, 89, 10, 66]
# Assume 1st element as max and min
max_val = numbers[0]
min_val = numbers[0]
# Compare each number with the max and min in each iteration
for num in numbers:
  #check if current element is greater than maximum value
    if num > max_val:
        max_val = num
  #check if current element is smaller than minimum value
    if num < min_val:
        min_val = num
# Display result of list of number , maximum and minimum values:
print("List:", numbers)
print("Max:", max_val)
print("Min:", min_val)

"""**Problem 4: Count Products Above a Price Threshold**

**Problem statement**: Count how many products have a price greater than 1000.

**Requirements** :A list of integers where each element represents the price of a product.
"""

# List of product prices in a list
prices = [450, 1200, 899, 1500, 300]
#intialize count to check how many products have a price greater than 1000.
count = 0
# Check each price of each product using iteration through each product's price
for price in prices:
  #check if current price greater than 1000 , if it is greater than 1000 increase count value by one
    if price > 1000:
        count += 1
# Display result of count of how many products have price greater than 1000:
print("Products above 1000:", count)

"""**Problem 5: Calculate Attendance Percentage**

**Problem Statement**: Calculate the attendance percentage from a list containing "P" (Present) and "A" (Absent).
"""

# Attendance list  containing P and A , "P" (Present) and "A" (Absent)
attendance = ["P", "P", "A", "P", "P"]
present_count = 0
# Count total  number of P
for day in attendance:
    if day == "P":
        present_count += 1
# Calculate percentage of attendance
total_days = len(attendance)
percentage = (present_count / total_days) * 100
# Display result:
print("Attendance Percentage:", percentage)

"""**Problem 6: Remove Duplicate Phone Numbers**

**Problem Statement**:You are given a list of phone numbers that may contain duplicates. Write a Python program to remove duplicate phone numbers and display only the unique phone numbers.
"""

#List of Phone numbers in a list
phone_numbers = [9876543210, 9123456789, 9876543210]
# Convert list to set to remove duplicates and store unique numbers
unique_numbers = set(phone_numbers)
# Display result:
print("Unique phone numbers:", unique_numbers)

"""**Problem 7: Count Character Frequency**

**Problem Statement** : Count how many times each character appears in a given string.
"""

# Input string
text = "python"
# intialize an Empty dictionary to store character and its count
freq = {}
# Count characters by traversing each character in a string
for ch in text:
    if ch in freq:
        freq[ch] += 1
    else:
        freq[ch] = 1
# Display result:
print(freq)

"""**Problem 8: Convert List to Tuple**

**Problem Statement** : Convert a list into a tuple and display it.
"""

# intialize the list with the given numbers
list = [10, 20, 30]
# Convert to tuple
t = tuple(list)
print("Tuple:", t)

"""**Problem 9: Check if a Key Exists in a Dictionary**

**Problem Statement**: Check whether a specific key exists in a dictionary.
"""

# Dictionary
employee = {
    "id": 101,
    "name": "Ravi",
    "salary": 75000}
# Key to check
key = "name"
# Check existence of employee
if key in employee:
    print("Employee exists")
else:
    print("Employee does not exist")

"""**Problem 10: Calculate Average Mark**

**Problem Statement**: Calculate the average marks of a student from a list of marks.
"""

# The list of marks
marks = [70, 75, 80, 65]
# Calculate average
total_marks = sum(marks)
count = len(marks)
average = total_marks / count
#display the average value
print("Average Marks:", average)